export const companies = [
  {
    name: "IndusTech Solutions",
    phoneNumber: "2266376637",
    balance: 100,
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    name: "TechNova Consulting",
    phoneNumber: "2266363000",
    balance: 150,
    city: "Bangalore",
    state: "Karnataka",
  },
  {
    name: "Zenith IT Services",
    phoneNumber: "8022945181",
    balance: 800,
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    name: "Apex Software Solutions",
    phoneNumber: "8022445566",
    balance: 900,
    city: "Chennai",
    state: "Tamil Nadu",
  },
  {
    name: "Quantum Digital Systems",
    phoneNumber: "1244567890",
    balance: 750,
    city: "Delhi",
    state: "Delhi",
  },
];

export const states = {
  AN: "Andaman and Nicobar Islands",
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CG: "Chandigarh",
  CH: "Chhattisgarh",
  DN: "Dadra and Nagar Haveli",
  DD: "Daman and Diu",
  DL: "Delhi",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JK: "Jammu and Kashmir",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  LA: "Ladakh",
  LD: "Lakshadweep",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manipur",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OR: "Odisha",
  PY: "Puducherry",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TS: "Telangana",
  TR: "Tripura",
  UP: "Uttar Pradesh",
  UK: "Uttarakhand",
  WB: "West Bengal",
};

export const unit = ["BAGS (BAG)", "PACKS (PAC)"];

export const gst = [
  "GST@0%",
  "IGST@0%",
  "GST@5%",
  "IGST@5%",
  "GST@12%",
  "IGST@12%",
  "GST@18%",
  "IGST@18%",
  "GST@28%",
  "IGST@28%",
];
